# Generated by Django 4.2.4 on 2023-08-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('categoria_codigo', models.CharField(db_column='Categoria_Codigo', max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=30, null=True)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula_cliente', models.CharField(db_column='Cedula_Cliente', max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=30, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('config', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('codigo_factura', models.CharField(db_column='Codigo_Factura', max_length=30, primary_key=True, serialize=False)),
                ('precio_unidad', models.FloatField(blank=True, db_column='Precio_Unidad', null=True)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('impuesto', models.FloatField(blank=True, db_column='Impuesto', null=True)),
                ('descuento', models.FloatField(blank=True, db_column='Descuento', null=True)),
            ],
            options={
                'db_table': 'factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('metodos_pago', models.CharField(db_column='Metodos_Pago', max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=30, null=True)),
            ],
            options={
                'db_table': 'metodo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codigo_pedido', models.CharField(db_column='Codigo_Pedido', max_length=30, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('total', models.IntegerField(blank=True, db_column='Total', null=True)),
                ('fecha_pedido', models.DateTimeField(blank=True, db_column='Fecha_Pedido', null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_column='Fecha_Entrega', null=True)),
                ('cedula_conductor', models.CharField(blank=True, db_column='Cedula_Conductor', max_length=30, null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedidoproducto', models.CharField(blank=True, db_column='Codigo_PedidoProducto', max_length=30, null=True)),
            ],
            options={
                'db_table': 'pedido_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo_producto', models.CharField(db_column='Codigo_Producto', max_length=30, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(blank=True, db_column='Nombre_Producto', max_length=30, null=True)),
                ('descripcion_producto', models.CharField(blank=True, db_column='Descripcion_Producto', max_length=30, null=True)),
                ('precio_unidad', models.FloatField(blank=True, db_column='Precio_Unidad', null=True)),
                ('no_existencia', models.IntegerField(blank=True, db_column='No_Existencia', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoFactura',
            fields=[
                ('codigo_productofactura', models.CharField(db_column='Codigo_ProductoFactura', max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'producto_factura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cedula_proveedor', models.CharField(db_column='Cedula_Proveedor', max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=30, null=True)),
                ('nombre_empresa', models.CharField(blank=True, db_column='Nombre_Empresa', max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=30, null=True)),
                ('telefono', models.IntegerField(blank=True, db_column='Telefono', null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=30, null=True)),
                ('estatus', models.CharField(blank=True, db_column='Estatus', max_length=30, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProveedorProductoentrante',
            fields=[
                ('codigo_productoentrante', models.CharField(db_column='Codigo_ProductoEntrante', max_length=30, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, db_column='Cantidad', null=True)),
                ('costo', models.FloatField(blank=True, db_column='Costo', null=True)),
                ('fecha_entrante', models.DateTimeField(blank=True, db_column='Fecha_Entrante', null=True)),
            ],
            options={
                'db_table': 'proveedor_productoentrante',
                'managed': False,
            },
        ),
    ]
